name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'jaffle_shop'

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  jaffle_shop:
    raw:
      +materialized: table
      +schema: bronze  
      +docs:
        node_color: '#cd7f32'
    
    staging:
      +materialized: "{{ 'view' if target.name == 'dev' else 'ephemeral' }}"  
      +schema: silver
      +docs:
        node_color: 'silver'
    
    marts:
      materialized: table
      database: "{{ target.database if target.name == 'dev' else 'pg_db' }}"
      schema: gold
      +docs:
        node_color: 'gold'


    
        